name: 'Generate Test Report'
description: 'Generate Test Report'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - uses: actions/download-artifact@v3
      with:
        path: ./artifacts
    - name: Extract Archives
      # This finds all .zip files in the ./artifacts
      # directory, including nested directories.
      # It then unzips every .zip to the root directory
      run: |
        find . -type f -name 'TestReport-*.zip' -exec unzip -q -o -d ../ {} \;
      shell: bash
      working-directory: ./artifacts
    - name: Build Reporter
      run: npm ci && npm run build
      shell: bash
      working-directory: ./core/test-reporter
    - name: Generate Report
      id: generate-report
      run: echo "REPORT_CONTENTS=$(node dist/index.js ../../test-report-*/*.json)" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ./core/test-reporter
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: ${{ needs.generate-report.outputs.REPORT_CONTENTS }}
          });
