name: 'Generate Test Report'
description: 'Generate Test Report'
inputs:
  token:
    description: 'GitHub token'
  repo:
    description: 'Repo owner and name'
  issue_number:
    description: 'Issue number'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - uses: actions/download-artifact@v3
      with:
        path: ./artifacts
    - name: Extract Archives
      # This finds all .zip files in the ./artifacts
      # directory, including nested directories.
      # It then unzips every .zip to the root directory
      run: |
        find . -type f -name 'TestReport-*.zip' -exec unzip -q -o -d ../ {} \;
      shell: bash
      working-directory: ./artifacts
    - name: test
      run: ls
      shell: bash
      working-directory: ./core
    - name: Build Reporter
      run: npm ci && npm run build
      shell: bash
      working-directory: ./core/test-reporter
    - name: Generate Report
      run: node dist/index.js "../../report.json"
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        REPO: ${{ inputs.repo }}
        ISSUE_NUMBER: ${{ inputs.issue_number }}
      shell: bash
      working-directory: ./core/test-reporter
