packages:
  - 'core'
  - 'docs'
  - 'packages/angular'
  - 'packages/angular-server'
  - 'packages/vue'
  - 'packages/vue-router'
  - 'packages/react'
  - 'packages/react-router'
  - 'packages/vue/test/build/**'
  - 'packages/react/test/build/**'
  - 'packages/angular/test/build/**'
